// Generated by LiveScript 1.3.1
var crypto;
crypto = require('crypto');
exports.generateToken = function (cb) {
    return crypto.randomBytes(32, function (err, buf) {
        if (err) {
            return cb(err);
        }
        return cb(null, buf.toString('hex'));
    });
};
exports.md5 = function (string) {
    return crypto.createHash('md5').update(string).digest('hex');
};
