// Generated by LiveScript 1.3.1
var cache, router, ef, errto, managerPrefix, getAnalytics;
cache = require('cache-manager').caching({
    store: 'memory',
    max: 1,
    ttl: 600
});
router = require('express').Router();
module.exports = router;
var request = require('promisingagent');
ef = require('../../ef');
errto = require('errto');
managerPrefix = require('config').proxy.manager;
getAnalytics = cache.wrap.bind(cache, 'analytics', function (cb) {
    request.get(managerPrefix + "/api/v2/analytics/count")
    .then(function (r) {
        return cb(null, (r != null ? r.body : void 8) || {});
    })
    .catch(cb)
});
router.get('/api/v2/analytics/count', function (req, res, next) {
    res.set('Content-Type', 'application/json; charset=utf-8');
    return getAnalytics(errto(next, function (result) {
        return res.send(result);
    }));
});
function bind$(obj, key, target) {
    return function () { return (target || obj)[key].apply(obj, arguments) };
}
