// Generated by LiveScript 1.3.1
var _, passport, auth, captchaRequired, router;
_ = require('lodash');
passport = require('../passport');
auth = require('../auth');
captchaRequired = require('../middlewares/captcha-required');
router = require('express').Router();
module.exports = router;
router.get('/test/cookie', function (req, res, next) {
    res.type('json');
    res.end(JSON.stringify({cookieInHeader: 'cookie' in req.headers}));
});
router.get('/test', passport.authenticate('bearer', {
    session: false,
    failWithError: true
}));
router.get('/test/pass', auth.pass());
router.get('/test/client', auth.client());
router.get('/test/user', auth.user());
router.get('/test/scope_b_c', auth.scope('b', 'c'));
router.get('/test/scope_c_d', auth.scope('c', 'd'));
router.use('/test', function (req, res) {
    return res.send(_.pick(req, ['url', 'user', 'authInfo', 'authPass']));
});
router.get('/api/user/:userId', auth.user());
router.get('/api/private/:userId', auth.owner());
router.get('/api/hello', auth.scope('c', 'd'));
router.get('/api/hi', auth.pass());
router.get('/api/hi_again', auth.pass(), captchaRequired);
router.get('/api/jsessionid', auth.pass());
