// Generated by LiveScript 1.3.1
var router;
router = require('express').Router();
module.exports = router;
router.use(require('./v2/upayment'));
router.use(require('./v2/users'));
router.use(require('./v2/register'));
router.use(require('./v2/cms'));
router.use(require('./v2/misc'));
router.use(require('./v2/loan'));
router.use(require('./v2/user'));
router.use(require('./v2/payment'));
router.use(require('./v2/route'));
router.use(require('./v2/coupon'));
router.use(require('./v2/survey'));
router.use(require('./mn/analytics'));
router.use(require('./wk/captcha'));
router.use(require('./v2/poolpay'));
router.use(require('./v2/message'));
router.use(require('./v2/creditassign'));

// v3
router.use(require('./v3/baofoo'));
router.use(require('./v3/invest'));