// Generated by LiveScript 1.3.1
var auth, ef, cache, router, config;
auth = require('../../auth');
ef = require('../../ef');
cache = require('../../cache');
router = require('express').Router();
module.exports = router;
config = require('config');
router.all('/api/v2/coupon/:userId/coupons', auth.owner());
router.get('/api/v2/coupon/:userId/coupons/byStatus', auth.owner());
router.post('/api/v2/coupon/:userId/redeemCoupon', auth.owner());
router.all('/api/v2/coupon/:userId/listCoupon', auth.owner());
router.all('/api/v2/coupon/:userId/listCoupons', auth.owner());
