// Generated by LiveScript 1.3.1
var token, ef;
token = require('../token');
ef = require('../ef');
module.exports = require('oauth2orize').exchange.clientCredentials(function(client, scope, done){
    var obj;
    if (!client) {
        return done(null);
    }
    if (client.id !== 'test') {
        scope = [];
    }
    client = {
        name: client.name,
        id: client.id
    };
    obj = {
        client: client,
        scope: scope
    };
    return ef(done, token.posta, obj, function(atoken){
        return done(null, atoken, null, obj);
    });
});
