// Generated by LiveScript 1.3.1
var cookieParser, debug, auth, ef, authUser, exports;
cookieParser = require('cookie-parser');
debug = require('debug')('myself');
auth = require('../auth');
ef = require('errto');
authUser = auth.user();
exports = module.exports = function (req, res, next) {
    if (req.url.indexOf('/MYSELF') < 0) {
        return next();
    }
    return authUser(req, res, ef(next, function () {
        var ref$, ref1$;
        if (((ref$ = req.user) != null ? ref$.id : void 8) != null && ((ref1$ = req.params) != null ? ref1$.userId : void 8) === 'MYSELF') {
            req.params.userId = req.user.id;
        }
        req.url = req.url.replace('/MYSELF', '/' + req.user.id);
        return next();
    }));
};
